---
abstract: 'Helper for running psgi applications with ubic and plackup'
author:
  - 'William Wolf <throughnothing@gmail.com>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300023, CPAN::Meta::Converter version 2.120921'
license: unrestricted
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Ubic-Service-ServerStarter
requires:
  Params::Validate: 0
  Plack: 0
  Server::Starter: 0.12
  Ubic::Daemon: 0
  Ubic::Service::Skeleton: 0
  base: 0
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/throughnothing/Ubic-Service-ServerStarter/issues
  repository: git://github.com/throughnothing/Ubic-Service-ServerStarter.git
version: 0.001
